/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2e' in SOPC Builder design 'controller'
 * SOPC Builder design path: C:/github/blastit/FPGA/controller.sopcinfo
 *
 * Generated: Mon Jul 23 22:23:12 PDT 2018
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00014820
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x11
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x11
#define ALT_CPU_NAME "nios2e"
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00014820
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x11
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x11
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_NIOS2_QSYS


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone III"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x15380
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x15380
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x15380
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "controller"


/*
 * bcd1_bcd configuration
 *
 */

#define ALT_MODULE_CLASS_bcd1_bcd altera_avalon_pio
#define BCD1_BCD_BASE 0x15270
#define BCD1_BCD_BIT_CLEARING_EDGE_REGISTER 0
#define BCD1_BCD_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BCD1_BCD_CAPTURE 1
#define BCD1_BCD_DATA_WIDTH 16
#define BCD1_BCD_DO_TEST_BENCH_WIRING 1
#define BCD1_BCD_DRIVEN_SIM_VALUE 0
#define BCD1_BCD_EDGE_TYPE "RISING"
#define BCD1_BCD_FREQ 50000000
#define BCD1_BCD_HAS_IN 1
#define BCD1_BCD_HAS_OUT 0
#define BCD1_BCD_HAS_TRI 0
#define BCD1_BCD_IRQ -1
#define BCD1_BCD_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BCD1_BCD_IRQ_TYPE "NONE"
#define BCD1_BCD_NAME "/dev/bcd1_bcd"
#define BCD1_BCD_RESET_VALUE 0
#define BCD1_BCD_SPAN 16
#define BCD1_BCD_TYPE "altera_avalon_pio"


/*
 * bcd1_bin configuration
 *
 */

#define ALT_MODULE_CLASS_bcd1_bin altera_avalon_pio
#define BCD1_BIN_BASE 0x15280
#define BCD1_BIN_BIT_CLEARING_EDGE_REGISTER 0
#define BCD1_BIN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BCD1_BIN_CAPTURE 0
#define BCD1_BIN_DATA_WIDTH 14
#define BCD1_BIN_DO_TEST_BENCH_WIRING 0
#define BCD1_BIN_DRIVEN_SIM_VALUE 0
#define BCD1_BIN_EDGE_TYPE "NONE"
#define BCD1_BIN_FREQ 50000000
#define BCD1_BIN_HAS_IN 0
#define BCD1_BIN_HAS_OUT 1
#define BCD1_BIN_HAS_TRI 0
#define BCD1_BIN_IRQ -1
#define BCD1_BIN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BCD1_BIN_IRQ_TYPE "NONE"
#define BCD1_BIN_NAME "/dev/bcd1_bin"
#define BCD1_BIN_RESET_VALUE 0
#define BCD1_BIN_SPAN 16
#define BCD1_BIN_TYPE "altera_avalon_pio"


/*
 * bcd1_control configuration
 *
 */

#define ALT_MODULE_CLASS_bcd1_control altera_avalon_pio
#define BCD1_CONTROL_BASE 0x150c0
#define BCD1_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define BCD1_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define BCD1_CONTROL_CAPTURE 0
#define BCD1_CONTROL_DATA_WIDTH 3
#define BCD1_CONTROL_DO_TEST_BENCH_WIRING 0
#define BCD1_CONTROL_DRIVEN_SIM_VALUE 0
#define BCD1_CONTROL_EDGE_TYPE "NONE"
#define BCD1_CONTROL_FREQ 50000000
#define BCD1_CONTROL_HAS_IN 0
#define BCD1_CONTROL_HAS_OUT 1
#define BCD1_CONTROL_HAS_TRI 0
#define BCD1_CONTROL_IRQ -1
#define BCD1_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BCD1_CONTROL_IRQ_TYPE "NONE"
#define BCD1_CONTROL_NAME "/dev/bcd1_control"
#define BCD1_CONTROL_RESET_VALUE 0
#define BCD1_CONTROL_SPAN 32
#define BCD1_CONTROL_TYPE "altera_avalon_pio"


/*
 * bcd1_counter configuration
 *
 */

#define ALT_MODULE_CLASS_bcd1_counter altera_avalon_pio
#define BCD1_COUNTER_BASE 0x15260
#define BCD1_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define BCD1_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BCD1_COUNTER_CAPTURE 1
#define BCD1_COUNTER_DATA_WIDTH 8
#define BCD1_COUNTER_DO_TEST_BENCH_WIRING 1
#define BCD1_COUNTER_DRIVEN_SIM_VALUE 0
#define BCD1_COUNTER_EDGE_TYPE "RISING"
#define BCD1_COUNTER_FREQ 50000000
#define BCD1_COUNTER_HAS_IN 1
#define BCD1_COUNTER_HAS_OUT 0
#define BCD1_COUNTER_HAS_TRI 0
#define BCD1_COUNTER_IRQ -1
#define BCD1_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BCD1_COUNTER_IRQ_TYPE "NONE"
#define BCD1_COUNTER_NAME "/dev/bcd1_counter"
#define BCD1_COUNTER_RESET_VALUE 0
#define BCD1_COUNTER_SPAN 16
#define BCD1_COUNTER_TYPE "altera_avalon_pio"


/*
 * bcd1_status configuration
 *
 */

#define ALT_MODULE_CLASS_bcd1_status altera_avalon_pio
#define BCD1_STATUS_BASE 0x15250
#define BCD1_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define BCD1_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BCD1_STATUS_CAPTURE 1
#define BCD1_STATUS_DATA_WIDTH 2
#define BCD1_STATUS_DO_TEST_BENCH_WIRING 1
#define BCD1_STATUS_DRIVEN_SIM_VALUE 0
#define BCD1_STATUS_EDGE_TYPE "RISING"
#define BCD1_STATUS_FREQ 50000000
#define BCD1_STATUS_HAS_IN 1
#define BCD1_STATUS_HAS_OUT 0
#define BCD1_STATUS_HAS_TRI 0
#define BCD1_STATUS_IRQ -1
#define BCD1_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BCD1_STATUS_IRQ_TYPE "NONE"
#define BCD1_STATUS_NAME "/dev/bcd1_status"
#define BCD1_STATUS_RESET_VALUE 0
#define BCD1_STATUS_SPAN 16
#define BCD1_STATUS_TYPE "altera_avalon_pio"


/*
 * daylight configuration
 *
 */

#define ALT_MODULE_CLASS_daylight altera_avalon_pio
#define DAYLIGHT_BASE 0x15370
#define DAYLIGHT_BIT_CLEARING_EDGE_REGISTER 0
#define DAYLIGHT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DAYLIGHT_CAPTURE 1
#define DAYLIGHT_DATA_WIDTH 1
#define DAYLIGHT_DO_TEST_BENCH_WIRING 1
#define DAYLIGHT_DRIVEN_SIM_VALUE 0
#define DAYLIGHT_EDGE_TYPE "RISING"
#define DAYLIGHT_FREQ 50000000
#define DAYLIGHT_HAS_IN 1
#define DAYLIGHT_HAS_OUT 0
#define DAYLIGHT_HAS_TRI 0
#define DAYLIGHT_IRQ -1
#define DAYLIGHT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DAYLIGHT_IRQ_TYPE "NONE"
#define DAYLIGHT_NAME "/dev/daylight"
#define DAYLIGHT_RESET_VALUE 0
#define DAYLIGHT_SPAN 16
#define DAYLIGHT_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 4
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x15380
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 32
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 32
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * leds_afr_brightness configuration
 *
 */

#define ALT_MODULE_CLASS_leds_afr_brightness altera_avalon_pio
#define LEDS_AFR_BRIGHTNESS_BASE 0x15190
#define LEDS_AFR_BRIGHTNESS_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_AFR_BRIGHTNESS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_AFR_BRIGHTNESS_CAPTURE 0
#define LEDS_AFR_BRIGHTNESS_DATA_WIDTH 8
#define LEDS_AFR_BRIGHTNESS_DO_TEST_BENCH_WIRING 0
#define LEDS_AFR_BRIGHTNESS_DRIVEN_SIM_VALUE 0
#define LEDS_AFR_BRIGHTNESS_EDGE_TYPE "NONE"
#define LEDS_AFR_BRIGHTNESS_FREQ 50000000
#define LEDS_AFR_BRIGHTNESS_HAS_IN 0
#define LEDS_AFR_BRIGHTNESS_HAS_OUT 1
#define LEDS_AFR_BRIGHTNESS_HAS_TRI 0
#define LEDS_AFR_BRIGHTNESS_IRQ -1
#define LEDS_AFR_BRIGHTNESS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_AFR_BRIGHTNESS_IRQ_TYPE "NONE"
#define LEDS_AFR_BRIGHTNESS_NAME "/dev/leds_afr_brightness"
#define LEDS_AFR_BRIGHTNESS_RESET_VALUE 0
#define LEDS_AFR_BRIGHTNESS_SPAN 16
#define LEDS_AFR_BRIGHTNESS_TYPE "altera_avalon_pio"


/*
 * leds_afr_control configuration
 *
 */

#define ALT_MODULE_CLASS_leds_afr_control altera_avalon_pio
#define LEDS_AFR_CONTROL_BASE 0x15000
#define LEDS_AFR_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_AFR_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LEDS_AFR_CONTROL_CAPTURE 0
#define LEDS_AFR_CONTROL_DATA_WIDTH 2
#define LEDS_AFR_CONTROL_DO_TEST_BENCH_WIRING 0
#define LEDS_AFR_CONTROL_DRIVEN_SIM_VALUE 0
#define LEDS_AFR_CONTROL_EDGE_TYPE "NONE"
#define LEDS_AFR_CONTROL_FREQ 50000000
#define LEDS_AFR_CONTROL_HAS_IN 0
#define LEDS_AFR_CONTROL_HAS_OUT 1
#define LEDS_AFR_CONTROL_HAS_TRI 0
#define LEDS_AFR_CONTROL_IRQ -1
#define LEDS_AFR_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_AFR_CONTROL_IRQ_TYPE "NONE"
#define LEDS_AFR_CONTROL_NAME "/dev/leds_afr_control"
#define LEDS_AFR_CONTROL_RESET_VALUE 0
#define LEDS_AFR_CONTROL_SPAN 32
#define LEDS_AFR_CONTROL_TYPE "altera_avalon_pio"


/*
 * leds_afr_counter configuration
 *
 */

#define ALT_MODULE_CLASS_leds_afr_counter altera_avalon_pio
#define LEDS_AFR_COUNTER_BASE 0x15150
#define LEDS_AFR_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_AFR_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_AFR_COUNTER_CAPTURE 1
#define LEDS_AFR_COUNTER_DATA_WIDTH 8
#define LEDS_AFR_COUNTER_DO_TEST_BENCH_WIRING 1
#define LEDS_AFR_COUNTER_DRIVEN_SIM_VALUE 0
#define LEDS_AFR_COUNTER_EDGE_TYPE "RISING"
#define LEDS_AFR_COUNTER_FREQ 50000000
#define LEDS_AFR_COUNTER_HAS_IN 1
#define LEDS_AFR_COUNTER_HAS_OUT 0
#define LEDS_AFR_COUNTER_HAS_TRI 0
#define LEDS_AFR_COUNTER_IRQ -1
#define LEDS_AFR_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_AFR_COUNTER_IRQ_TYPE "NONE"
#define LEDS_AFR_COUNTER_NAME "/dev/leds_afr_counter"
#define LEDS_AFR_COUNTER_RESET_VALUE 0
#define LEDS_AFR_COUNTER_SPAN 16
#define LEDS_AFR_COUNTER_TYPE "altera_avalon_pio"


/*
 * leds_afr_sel_addr configuration
 *
 */

#define ALT_MODULE_CLASS_leds_afr_sel_addr altera_avalon_pio
#define LEDS_AFR_SEL_ADDR_BASE 0x15170
#define LEDS_AFR_SEL_ADDR_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_AFR_SEL_ADDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_AFR_SEL_ADDR_CAPTURE 0
#define LEDS_AFR_SEL_ADDR_DATA_WIDTH 6
#define LEDS_AFR_SEL_ADDR_DO_TEST_BENCH_WIRING 0
#define LEDS_AFR_SEL_ADDR_DRIVEN_SIM_VALUE 0
#define LEDS_AFR_SEL_ADDR_EDGE_TYPE "NONE"
#define LEDS_AFR_SEL_ADDR_FREQ 50000000
#define LEDS_AFR_SEL_ADDR_HAS_IN 0
#define LEDS_AFR_SEL_ADDR_HAS_OUT 1
#define LEDS_AFR_SEL_ADDR_HAS_TRI 0
#define LEDS_AFR_SEL_ADDR_IRQ -1
#define LEDS_AFR_SEL_ADDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_AFR_SEL_ADDR_IRQ_TYPE "NONE"
#define LEDS_AFR_SEL_ADDR_NAME "/dev/leds_afr_sel_addr"
#define LEDS_AFR_SEL_ADDR_RESET_VALUE 0
#define LEDS_AFR_SEL_ADDR_SPAN 16
#define LEDS_AFR_SEL_ADDR_TYPE "altera_avalon_pio"


/*
 * leds_boost_brightness configuration
 *
 */

#define ALT_MODULE_CLASS_leds_boost_brightness altera_avalon_pio
#define LEDS_BOOST_BRIGHTNESS_BASE 0x151a0
#define LEDS_BOOST_BRIGHTNESS_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BOOST_BRIGHTNESS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_BOOST_BRIGHTNESS_CAPTURE 0
#define LEDS_BOOST_BRIGHTNESS_DATA_WIDTH 8
#define LEDS_BOOST_BRIGHTNESS_DO_TEST_BENCH_WIRING 0
#define LEDS_BOOST_BRIGHTNESS_DRIVEN_SIM_VALUE 0
#define LEDS_BOOST_BRIGHTNESS_EDGE_TYPE "NONE"
#define LEDS_BOOST_BRIGHTNESS_FREQ 50000000
#define LEDS_BOOST_BRIGHTNESS_HAS_IN 0
#define LEDS_BOOST_BRIGHTNESS_HAS_OUT 1
#define LEDS_BOOST_BRIGHTNESS_HAS_TRI 0
#define LEDS_BOOST_BRIGHTNESS_IRQ -1
#define LEDS_BOOST_BRIGHTNESS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_BOOST_BRIGHTNESS_IRQ_TYPE "NONE"
#define LEDS_BOOST_BRIGHTNESS_NAME "/dev/leds_boost_brightness"
#define LEDS_BOOST_BRIGHTNESS_RESET_VALUE 0
#define LEDS_BOOST_BRIGHTNESS_SPAN 16
#define LEDS_BOOST_BRIGHTNESS_TYPE "altera_avalon_pio"


/*
 * leds_boost_control configuration
 *
 */

#define ALT_MODULE_CLASS_leds_boost_control altera_avalon_pio
#define LEDS_BOOST_CONTROL_BASE 0x15020
#define LEDS_BOOST_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BOOST_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LEDS_BOOST_CONTROL_CAPTURE 0
#define LEDS_BOOST_CONTROL_DATA_WIDTH 2
#define LEDS_BOOST_CONTROL_DO_TEST_BENCH_WIRING 0
#define LEDS_BOOST_CONTROL_DRIVEN_SIM_VALUE 0
#define LEDS_BOOST_CONTROL_EDGE_TYPE "NONE"
#define LEDS_BOOST_CONTROL_FREQ 50000000
#define LEDS_BOOST_CONTROL_HAS_IN 0
#define LEDS_BOOST_CONTROL_HAS_OUT 1
#define LEDS_BOOST_CONTROL_HAS_TRI 0
#define LEDS_BOOST_CONTROL_IRQ -1
#define LEDS_BOOST_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_BOOST_CONTROL_IRQ_TYPE "NONE"
#define LEDS_BOOST_CONTROL_NAME "/dev/leds_boost_control"
#define LEDS_BOOST_CONTROL_RESET_VALUE 0
#define LEDS_BOOST_CONTROL_SPAN 32
#define LEDS_BOOST_CONTROL_TYPE "altera_avalon_pio"


/*
 * leds_boost_counter configuration
 *
 */

#define ALT_MODULE_CLASS_leds_boost_counter altera_avalon_pio
#define LEDS_BOOST_COUNTER_BASE 0x15160
#define LEDS_BOOST_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BOOST_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_BOOST_COUNTER_CAPTURE 1
#define LEDS_BOOST_COUNTER_DATA_WIDTH 8
#define LEDS_BOOST_COUNTER_DO_TEST_BENCH_WIRING 1
#define LEDS_BOOST_COUNTER_DRIVEN_SIM_VALUE 0
#define LEDS_BOOST_COUNTER_EDGE_TYPE "RISING"
#define LEDS_BOOST_COUNTER_FREQ 50000000
#define LEDS_BOOST_COUNTER_HAS_IN 1
#define LEDS_BOOST_COUNTER_HAS_OUT 0
#define LEDS_BOOST_COUNTER_HAS_TRI 0
#define LEDS_BOOST_COUNTER_IRQ -1
#define LEDS_BOOST_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_BOOST_COUNTER_IRQ_TYPE "NONE"
#define LEDS_BOOST_COUNTER_NAME "/dev/leds_boost_counter"
#define LEDS_BOOST_COUNTER_RESET_VALUE 0
#define LEDS_BOOST_COUNTER_SPAN 16
#define LEDS_BOOST_COUNTER_TYPE "altera_avalon_pio"


/*
 * leds_boost_sel_addr configuration
 *
 */

#define ALT_MODULE_CLASS_leds_boost_sel_addr altera_avalon_pio
#define LEDS_BOOST_SEL_ADDR_BASE 0x15180
#define LEDS_BOOST_SEL_ADDR_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BOOST_SEL_ADDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_BOOST_SEL_ADDR_CAPTURE 0
#define LEDS_BOOST_SEL_ADDR_DATA_WIDTH 6
#define LEDS_BOOST_SEL_ADDR_DO_TEST_BENCH_WIRING 0
#define LEDS_BOOST_SEL_ADDR_DRIVEN_SIM_VALUE 0
#define LEDS_BOOST_SEL_ADDR_EDGE_TYPE "NONE"
#define LEDS_BOOST_SEL_ADDR_FREQ 50000000
#define LEDS_BOOST_SEL_ADDR_HAS_IN 0
#define LEDS_BOOST_SEL_ADDR_HAS_OUT 1
#define LEDS_BOOST_SEL_ADDR_HAS_TRI 0
#define LEDS_BOOST_SEL_ADDR_IRQ -1
#define LEDS_BOOST_SEL_ADDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_BOOST_SEL_ADDR_IRQ_TYPE "NONE"
#define LEDS_BOOST_SEL_ADDR_NAME "/dev/leds_boost_sel_addr"
#define LEDS_BOOST_SEL_ADDR_RESET_VALUE 0
#define LEDS_BOOST_SEL_ADDR_SPAN 16
#define LEDS_BOOST_SEL_ADDR_TYPE "altera_avalon_pio"


/*
 * leds_counter_status configuration
 *
 */

#define ALT_MODULE_CLASS_leds_counter_status altera_avalon_pio
#define LEDS_COUNTER_STATUS_BASE 0x15140
#define LEDS_COUNTER_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_COUNTER_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_COUNTER_STATUS_CAPTURE 1
#define LEDS_COUNTER_STATUS_DATA_WIDTH 2
#define LEDS_COUNTER_STATUS_DO_TEST_BENCH_WIRING 1
#define LEDS_COUNTER_STATUS_DRIVEN_SIM_VALUE 0
#define LEDS_COUNTER_STATUS_EDGE_TYPE "RISING"
#define LEDS_COUNTER_STATUS_FREQ 50000000
#define LEDS_COUNTER_STATUS_HAS_IN 1
#define LEDS_COUNTER_STATUS_HAS_OUT 0
#define LEDS_COUNTER_STATUS_HAS_TRI 0
#define LEDS_COUNTER_STATUS_IRQ -1
#define LEDS_COUNTER_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_COUNTER_STATUS_IRQ_TYPE "NONE"
#define LEDS_COUNTER_STATUS_NAME "/dev/leds_counter_status"
#define LEDS_COUNTER_STATUS_RESET_VALUE 0
#define LEDS_COUNTER_STATUS_SPAN 16
#define LEDS_COUNTER_STATUS_TYPE "altera_avalon_pio"


/*
 * leds_reset_control configuration
 *
 */

#define ALT_MODULE_CLASS_leds_reset_control altera_avalon_pio
#define LEDS_RESET_CONTROL_BASE 0x15040
#define LEDS_RESET_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_RESET_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LEDS_RESET_CONTROL_CAPTURE 0
#define LEDS_RESET_CONTROL_DATA_WIDTH 4
#define LEDS_RESET_CONTROL_DO_TEST_BENCH_WIRING 0
#define LEDS_RESET_CONTROL_DRIVEN_SIM_VALUE 0
#define LEDS_RESET_CONTROL_EDGE_TYPE "NONE"
#define LEDS_RESET_CONTROL_FREQ 50000000
#define LEDS_RESET_CONTROL_HAS_IN 0
#define LEDS_RESET_CONTROL_HAS_OUT 1
#define LEDS_RESET_CONTROL_HAS_TRI 0
#define LEDS_RESET_CONTROL_IRQ -1
#define LEDS_RESET_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_RESET_CONTROL_IRQ_TYPE "NONE"
#define LEDS_RESET_CONTROL_NAME "/dev/leds_reset_control"
#define LEDS_RESET_CONTROL_RESET_VALUE 0
#define LEDS_RESET_CONTROL_SPAN 32
#define LEDS_RESET_CONTROL_TYPE "altera_avalon_pio"


/*
 * onchip_ram configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_ram altera_avalon_onchip_memory2
#define ONCHIP_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_RAM_BASE 0x0
#define ONCHIP_RAM_CONTENTS_INFO ""
#define ONCHIP_RAM_DUAL_PORT 0
#define ONCHIP_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_RAM_INIT_CONTENTS_FILE "controller_onchip_ram"
#define ONCHIP_RAM_INIT_MEM_CONTENT 1
#define ONCHIP_RAM_INSTANCE_ID "NONE"
#define ONCHIP_RAM_IRQ -1
#define ONCHIP_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_RAM_NAME "/dev/onchip_ram"
#define ONCHIP_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_RAM_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_RAM_SINGLE_CLOCK_OP 0
#define ONCHIP_RAM_SIZE_MULTIPLE 1
#define ONCHIP_RAM_SIZE_VALUE 49152
#define ONCHIP_RAM_SPAN 49152
#define ONCHIP_RAM_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_RAM_WRITABLE 1


/*
 * sseg_brightness_afr configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_brightness_afr altera_avalon_pio
#define SSEG_BRIGHTNESS_AFR_BASE 0x15220
#define SSEG_BRIGHTNESS_AFR_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_BRIGHTNESS_AFR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_BRIGHTNESS_AFR_CAPTURE 0
#define SSEG_BRIGHTNESS_AFR_DATA_WIDTH 8
#define SSEG_BRIGHTNESS_AFR_DO_TEST_BENCH_WIRING 0
#define SSEG_BRIGHTNESS_AFR_DRIVEN_SIM_VALUE 0
#define SSEG_BRIGHTNESS_AFR_EDGE_TYPE "NONE"
#define SSEG_BRIGHTNESS_AFR_FREQ 50000000
#define SSEG_BRIGHTNESS_AFR_HAS_IN 0
#define SSEG_BRIGHTNESS_AFR_HAS_OUT 1
#define SSEG_BRIGHTNESS_AFR_HAS_TRI 0
#define SSEG_BRIGHTNESS_AFR_IRQ -1
#define SSEG_BRIGHTNESS_AFR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_BRIGHTNESS_AFR_IRQ_TYPE "NONE"
#define SSEG_BRIGHTNESS_AFR_NAME "/dev/sseg_brightness_afr"
#define SSEG_BRIGHTNESS_AFR_RESET_VALUE 0
#define SSEG_BRIGHTNESS_AFR_SPAN 16
#define SSEG_BRIGHTNESS_AFR_TYPE "altera_avalon_pio"


/*
 * sseg_brightness_boost configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_brightness_boost altera_avalon_pio
#define SSEG_BRIGHTNESS_BOOST_BASE 0x15230
#define SSEG_BRIGHTNESS_BOOST_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_BRIGHTNESS_BOOST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_BRIGHTNESS_BOOST_CAPTURE 0
#define SSEG_BRIGHTNESS_BOOST_DATA_WIDTH 8
#define SSEG_BRIGHTNESS_BOOST_DO_TEST_BENCH_WIRING 0
#define SSEG_BRIGHTNESS_BOOST_DRIVEN_SIM_VALUE 0
#define SSEG_BRIGHTNESS_BOOST_EDGE_TYPE "NONE"
#define SSEG_BRIGHTNESS_BOOST_FREQ 50000000
#define SSEG_BRIGHTNESS_BOOST_HAS_IN 0
#define SSEG_BRIGHTNESS_BOOST_HAS_OUT 1
#define SSEG_BRIGHTNESS_BOOST_HAS_TRI 0
#define SSEG_BRIGHTNESS_BOOST_IRQ -1
#define SSEG_BRIGHTNESS_BOOST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_BRIGHTNESS_BOOST_IRQ_TYPE "NONE"
#define SSEG_BRIGHTNESS_BOOST_NAME "/dev/sseg_brightness_boost"
#define SSEG_BRIGHTNESS_BOOST_RESET_VALUE 0
#define SSEG_BRIGHTNESS_BOOST_SPAN 16
#define SSEG_BRIGHTNESS_BOOST_TYPE "altera_avalon_pio"


/*
 * sseg_brightness_coolant configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_brightness_coolant altera_avalon_pio
#define SSEG_BRIGHTNESS_COOLANT_BASE 0x15200
#define SSEG_BRIGHTNESS_COOLANT_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_BRIGHTNESS_COOLANT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_BRIGHTNESS_COOLANT_CAPTURE 0
#define SSEG_BRIGHTNESS_COOLANT_DATA_WIDTH 8
#define SSEG_BRIGHTNESS_COOLANT_DO_TEST_BENCH_WIRING 0
#define SSEG_BRIGHTNESS_COOLANT_DRIVEN_SIM_VALUE 0
#define SSEG_BRIGHTNESS_COOLANT_EDGE_TYPE "NONE"
#define SSEG_BRIGHTNESS_COOLANT_FREQ 50000000
#define SSEG_BRIGHTNESS_COOLANT_HAS_IN 0
#define SSEG_BRIGHTNESS_COOLANT_HAS_OUT 1
#define SSEG_BRIGHTNESS_COOLANT_HAS_TRI 0
#define SSEG_BRIGHTNESS_COOLANT_IRQ -1
#define SSEG_BRIGHTNESS_COOLANT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_BRIGHTNESS_COOLANT_IRQ_TYPE "NONE"
#define SSEG_BRIGHTNESS_COOLANT_NAME "/dev/sseg_brightness_coolant"
#define SSEG_BRIGHTNESS_COOLANT_RESET_VALUE 0
#define SSEG_BRIGHTNESS_COOLANT_SPAN 16
#define SSEG_BRIGHTNESS_COOLANT_TYPE "altera_avalon_pio"


/*
 * sseg_brightness_oil configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_brightness_oil altera_avalon_pio
#define SSEG_BRIGHTNESS_OIL_BASE 0x15210
#define SSEG_BRIGHTNESS_OIL_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_BRIGHTNESS_OIL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_BRIGHTNESS_OIL_CAPTURE 0
#define SSEG_BRIGHTNESS_OIL_DATA_WIDTH 8
#define SSEG_BRIGHTNESS_OIL_DO_TEST_BENCH_WIRING 0
#define SSEG_BRIGHTNESS_OIL_DRIVEN_SIM_VALUE 0
#define SSEG_BRIGHTNESS_OIL_EDGE_TYPE "NONE"
#define SSEG_BRIGHTNESS_OIL_FREQ 50000000
#define SSEG_BRIGHTNESS_OIL_HAS_IN 0
#define SSEG_BRIGHTNESS_OIL_HAS_OUT 1
#define SSEG_BRIGHTNESS_OIL_HAS_TRI 0
#define SSEG_BRIGHTNESS_OIL_IRQ -1
#define SSEG_BRIGHTNESS_OIL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_BRIGHTNESS_OIL_IRQ_TYPE "NONE"
#define SSEG_BRIGHTNESS_OIL_NAME "/dev/sseg_brightness_oil"
#define SSEG_BRIGHTNESS_OIL_RESET_VALUE 0
#define SSEG_BRIGHTNESS_OIL_SPAN 16
#define SSEG_BRIGHTNESS_OIL_TYPE "altera_avalon_pio"


/*
 * sseg_counter configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_counter altera_avalon_pio
#define SSEG_COUNTER_BASE 0x151c0
#define SSEG_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_COUNTER_CAPTURE 1
#define SSEG_COUNTER_DATA_WIDTH 8
#define SSEG_COUNTER_DO_TEST_BENCH_WIRING 1
#define SSEG_COUNTER_DRIVEN_SIM_VALUE 0
#define SSEG_COUNTER_EDGE_TYPE "RISING"
#define SSEG_COUNTER_FREQ 50000000
#define SSEG_COUNTER_HAS_IN 1
#define SSEG_COUNTER_HAS_OUT 0
#define SSEG_COUNTER_HAS_TRI 0
#define SSEG_COUNTER_IRQ -1
#define SSEG_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_COUNTER_IRQ_TYPE "NONE"
#define SSEG_COUNTER_NAME "/dev/sseg_counter"
#define SSEG_COUNTER_RESET_VALUE 0
#define SSEG_COUNTER_SPAN 16
#define SSEG_COUNTER_TYPE "altera_avalon_pio"


/*
 * sseg_counter_of configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_counter_of altera_avalon_pio
#define SSEG_COUNTER_OF_BASE 0x151b0
#define SSEG_COUNTER_OF_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_COUNTER_OF_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_COUNTER_OF_CAPTURE 1
#define SSEG_COUNTER_OF_DATA_WIDTH 1
#define SSEG_COUNTER_OF_DO_TEST_BENCH_WIRING 1
#define SSEG_COUNTER_OF_DRIVEN_SIM_VALUE 0
#define SSEG_COUNTER_OF_EDGE_TYPE "RISING"
#define SSEG_COUNTER_OF_FREQ 50000000
#define SSEG_COUNTER_OF_HAS_IN 1
#define SSEG_COUNTER_OF_HAS_OUT 0
#define SSEG_COUNTER_OF_HAS_TRI 0
#define SSEG_COUNTER_OF_IRQ -1
#define SSEG_COUNTER_OF_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_COUNTER_OF_IRQ_TYPE "NONE"
#define SSEG_COUNTER_OF_NAME "/dev/sseg_counter_of"
#define SSEG_COUNTER_OF_RESET_VALUE 0
#define SSEG_COUNTER_OF_SPAN 16
#define SSEG_COUNTER_OF_TYPE "altera_avalon_pio"


/*
 * sseg_reset_control configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_reset_control altera_avalon_pio
#define SSEG_RESET_CONTROL_BASE 0x15060
#define SSEG_RESET_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_RESET_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define SSEG_RESET_CONTROL_CAPTURE 0
#define SSEG_RESET_CONTROL_DATA_WIDTH 5
#define SSEG_RESET_CONTROL_DO_TEST_BENCH_WIRING 0
#define SSEG_RESET_CONTROL_DRIVEN_SIM_VALUE 0
#define SSEG_RESET_CONTROL_EDGE_TYPE "NONE"
#define SSEG_RESET_CONTROL_FREQ 50000000
#define SSEG_RESET_CONTROL_HAS_IN 0
#define SSEG_RESET_CONTROL_HAS_OUT 1
#define SSEG_RESET_CONTROL_HAS_TRI 0
#define SSEG_RESET_CONTROL_IRQ -1
#define SSEG_RESET_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_RESET_CONTROL_IRQ_TYPE "NONE"
#define SSEG_RESET_CONTROL_NAME "/dev/sseg_reset_control"
#define SSEG_RESET_CONTROL_RESET_VALUE 0
#define SSEG_RESET_CONTROL_SPAN 32
#define SSEG_RESET_CONTROL_TYPE "altera_avalon_pio"


/*
 * sseg_sel_addr configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_sel_addr altera_avalon_pio
#define SSEG_SEL_ADDR_BASE 0x151f0
#define SSEG_SEL_ADDR_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_SEL_ADDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_SEL_ADDR_CAPTURE 0
#define SSEG_SEL_ADDR_DATA_WIDTH 2
#define SSEG_SEL_ADDR_DO_TEST_BENCH_WIRING 0
#define SSEG_SEL_ADDR_DRIVEN_SIM_VALUE 0
#define SSEG_SEL_ADDR_EDGE_TYPE "NONE"
#define SSEG_SEL_ADDR_FREQ 50000000
#define SSEG_SEL_ADDR_HAS_IN 0
#define SSEG_SEL_ADDR_HAS_OUT 1
#define SSEG_SEL_ADDR_HAS_TRI 0
#define SSEG_SEL_ADDR_IRQ -1
#define SSEG_SEL_ADDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_SEL_ADDR_IRQ_TYPE "NONE"
#define SSEG_SEL_ADDR_NAME "/dev/sseg_sel_addr"
#define SSEG_SEL_ADDR_RESET_VALUE 0
#define SSEG_SEL_ADDR_SPAN 16
#define SSEG_SEL_ADDR_TYPE "altera_avalon_pio"


/*
 * sseg_wr_control configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_wr_control altera_avalon_pio
#define SSEG_WR_CONTROL_BASE 0x151e0
#define SSEG_WR_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_WR_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_WR_CONTROL_CAPTURE 0
#define SSEG_WR_CONTROL_DATA_WIDTH 4
#define SSEG_WR_CONTROL_DO_TEST_BENCH_WIRING 0
#define SSEG_WR_CONTROL_DRIVEN_SIM_VALUE 0
#define SSEG_WR_CONTROL_EDGE_TYPE "NONE"
#define SSEG_WR_CONTROL_FREQ 50000000
#define SSEG_WR_CONTROL_HAS_IN 0
#define SSEG_WR_CONTROL_HAS_OUT 1
#define SSEG_WR_CONTROL_HAS_TRI 0
#define SSEG_WR_CONTROL_IRQ -1
#define SSEG_WR_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_WR_CONTROL_IRQ_TYPE "NONE"
#define SSEG_WR_CONTROL_NAME "/dev/sseg_wr_control"
#define SSEG_WR_CONTROL_RESET_VALUE 0
#define SSEG_WR_CONTROL_SPAN 16
#define SSEG_WR_CONTROL_TYPE "altera_avalon_pio"


/*
 * sseg_wr_val configuration
 *
 */

#define ALT_MODULE_CLASS_sseg_wr_val altera_avalon_pio
#define SSEG_WR_VAL_BASE 0x151d0
#define SSEG_WR_VAL_BIT_CLEARING_EDGE_REGISTER 0
#define SSEG_WR_VAL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SSEG_WR_VAL_CAPTURE 0
#define SSEG_WR_VAL_DATA_WIDTH 7
#define SSEG_WR_VAL_DO_TEST_BENCH_WIRING 0
#define SSEG_WR_VAL_DRIVEN_SIM_VALUE 0
#define SSEG_WR_VAL_EDGE_TYPE "NONE"
#define SSEG_WR_VAL_FREQ 50000000
#define SSEG_WR_VAL_HAS_IN 0
#define SSEG_WR_VAL_HAS_OUT 1
#define SSEG_WR_VAL_HAS_TRI 0
#define SSEG_WR_VAL_IRQ -1
#define SSEG_WR_VAL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SSEG_WR_VAL_IRQ_TYPE "NONE"
#define SSEG_WR_VAL_NAME "/dev/sseg_wr_val"
#define SSEG_WR_VAL_RESET_VALUE 0
#define SSEG_WR_VAL_SPAN 16
#define SSEG_WR_VAL_TYPE "altera_avalon_pio"


/*
 * status_led_en configuration
 *
 */

#define ALT_MODULE_CLASS_status_led_en altera_avalon_pio
#define STATUS_LED_EN_BASE 0x15080
#define STATUS_LED_EN_BIT_CLEARING_EDGE_REGISTER 0
#define STATUS_LED_EN_BIT_MODIFYING_OUTPUT_REGISTER 1
#define STATUS_LED_EN_CAPTURE 0
#define STATUS_LED_EN_DATA_WIDTH 4
#define STATUS_LED_EN_DO_TEST_BENCH_WIRING 0
#define STATUS_LED_EN_DRIVEN_SIM_VALUE 0
#define STATUS_LED_EN_EDGE_TYPE "NONE"
#define STATUS_LED_EN_FREQ 50000000
#define STATUS_LED_EN_HAS_IN 0
#define STATUS_LED_EN_HAS_OUT 1
#define STATUS_LED_EN_HAS_TRI 0
#define STATUS_LED_EN_IRQ -1
#define STATUS_LED_EN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define STATUS_LED_EN_IRQ_TYPE "NONE"
#define STATUS_LED_EN_NAME "/dev/status_led_en"
#define STATUS_LED_EN_RESET_VALUE 0
#define STATUS_LED_EN_SPAN 32
#define STATUS_LED_EN_TYPE "altera_avalon_pio"


/*
 * sysid_c001 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_c001 altera_avalon_sysid_qsys
#define SYSID_C001_BASE 0x15388
#define SYSID_C001_ID 49153
#define SYSID_C001_IRQ -1
#define SYSID_C001_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_C001_NAME "/dev/sysid_c001"
#define SYSID_C001_SPAN 8
#define SYSID_C001_TIMESTAMP 1532406577
#define SYSID_C001_TYPE "altera_avalon_sysid_qsys"


/*
 * tc1_m configuration
 *
 */

#define ALT_MODULE_CLASS_tc1_m altera_avalon_pio
#define TC1_M_BASE 0x15360
#define TC1_M_BIT_CLEARING_EDGE_REGISTER 0
#define TC1_M_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC1_M_CAPTURE 0
#define TC1_M_DATA_WIDTH 32
#define TC1_M_DO_TEST_BENCH_WIRING 0
#define TC1_M_DRIVEN_SIM_VALUE 0
#define TC1_M_EDGE_TYPE "NONE"
#define TC1_M_FREQ 50000000
#define TC1_M_HAS_IN 0
#define TC1_M_HAS_OUT 1
#define TC1_M_HAS_TRI 0
#define TC1_M_IRQ -1
#define TC1_M_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC1_M_IRQ_TYPE "NONE"
#define TC1_M_NAME "/dev/tc1_m"
#define TC1_M_RESET_VALUE 0
#define TC1_M_SPAN 16
#define TC1_M_TYPE "altera_avalon_pio"


/*
 * tc1_status configuration
 *
 */

#define ALT_MODULE_CLASS_tc1_status altera_avalon_pio
#define TC1_STATUS_BASE 0x15320
#define TC1_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define TC1_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC1_STATUS_CAPTURE 1
#define TC1_STATUS_DATA_WIDTH 25
#define TC1_STATUS_DO_TEST_BENCH_WIRING 1
#define TC1_STATUS_DRIVEN_SIM_VALUE 0
#define TC1_STATUS_EDGE_TYPE "RISING"
#define TC1_STATUS_FREQ 50000000
#define TC1_STATUS_HAS_IN 1
#define TC1_STATUS_HAS_OUT 0
#define TC1_STATUS_HAS_TRI 0
#define TC1_STATUS_IRQ -1
#define TC1_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC1_STATUS_IRQ_TYPE "NONE"
#define TC1_STATUS_NAME "/dev/tc1_status"
#define TC1_STATUS_RESET_VALUE 0
#define TC1_STATUS_SPAN 16
#define TC1_STATUS_TYPE "altera_avalon_pio"


/*
 * tc2_m configuration
 *
 */

#define ALT_MODULE_CLASS_tc2_m altera_avalon_pio
#define TC2_M_BASE 0x15350
#define TC2_M_BIT_CLEARING_EDGE_REGISTER 0
#define TC2_M_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC2_M_CAPTURE 0
#define TC2_M_DATA_WIDTH 32
#define TC2_M_DO_TEST_BENCH_WIRING 0
#define TC2_M_DRIVEN_SIM_VALUE 0
#define TC2_M_EDGE_TYPE "NONE"
#define TC2_M_FREQ 50000000
#define TC2_M_HAS_IN 0
#define TC2_M_HAS_OUT 1
#define TC2_M_HAS_TRI 0
#define TC2_M_IRQ -1
#define TC2_M_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC2_M_IRQ_TYPE "NONE"
#define TC2_M_NAME "/dev/tc2_m"
#define TC2_M_RESET_VALUE 0
#define TC2_M_SPAN 16
#define TC2_M_TYPE "altera_avalon_pio"


/*
 * tc2_status configuration
 *
 */

#define ALT_MODULE_CLASS_tc2_status altera_avalon_pio
#define TC2_STATUS_BASE 0x15310
#define TC2_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define TC2_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC2_STATUS_CAPTURE 1
#define TC2_STATUS_DATA_WIDTH 25
#define TC2_STATUS_DO_TEST_BENCH_WIRING 1
#define TC2_STATUS_DRIVEN_SIM_VALUE 0
#define TC2_STATUS_EDGE_TYPE "RISING"
#define TC2_STATUS_FREQ 50000000
#define TC2_STATUS_HAS_IN 1
#define TC2_STATUS_HAS_OUT 0
#define TC2_STATUS_HAS_TRI 0
#define TC2_STATUS_IRQ -1
#define TC2_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC2_STATUS_IRQ_TYPE "NONE"
#define TC2_STATUS_NAME "/dev/tc2_status"
#define TC2_STATUS_RESET_VALUE 0
#define TC2_STATUS_SPAN 16
#define TC2_STATUS_TYPE "altera_avalon_pio"


/*
 * tc3_m configuration
 *
 */

#define ALT_MODULE_CLASS_tc3_m altera_avalon_pio
#define TC3_M_BASE 0x15340
#define TC3_M_BIT_CLEARING_EDGE_REGISTER 0
#define TC3_M_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC3_M_CAPTURE 0
#define TC3_M_DATA_WIDTH 32
#define TC3_M_DO_TEST_BENCH_WIRING 0
#define TC3_M_DRIVEN_SIM_VALUE 0
#define TC3_M_EDGE_TYPE "NONE"
#define TC3_M_FREQ 50000000
#define TC3_M_HAS_IN 0
#define TC3_M_HAS_OUT 1
#define TC3_M_HAS_TRI 0
#define TC3_M_IRQ -1
#define TC3_M_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC3_M_IRQ_TYPE "NONE"
#define TC3_M_NAME "/dev/tc3_m"
#define TC3_M_RESET_VALUE 0
#define TC3_M_SPAN 16
#define TC3_M_TYPE "altera_avalon_pio"


/*
 * tc3_status configuration
 *
 */

#define ALT_MODULE_CLASS_tc3_status altera_avalon_pio
#define TC3_STATUS_BASE 0x15300
#define TC3_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define TC3_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC3_STATUS_CAPTURE 1
#define TC3_STATUS_DATA_WIDTH 25
#define TC3_STATUS_DO_TEST_BENCH_WIRING 1
#define TC3_STATUS_DRIVEN_SIM_VALUE 0
#define TC3_STATUS_EDGE_TYPE "RISING"
#define TC3_STATUS_FREQ 50000000
#define TC3_STATUS_HAS_IN 1
#define TC3_STATUS_HAS_OUT 0
#define TC3_STATUS_HAS_TRI 0
#define TC3_STATUS_IRQ -1
#define TC3_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC3_STATUS_IRQ_TYPE "NONE"
#define TC3_STATUS_NAME "/dev/tc3_status"
#define TC3_STATUS_RESET_VALUE 0
#define TC3_STATUS_SPAN 16
#define TC3_STATUS_TYPE "altera_avalon_pio"


/*
 * tc4_m configuration
 *
 */

#define ALT_MODULE_CLASS_tc4_m altera_avalon_pio
#define TC4_M_BASE 0x15330
#define TC4_M_BIT_CLEARING_EDGE_REGISTER 0
#define TC4_M_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC4_M_CAPTURE 0
#define TC4_M_DATA_WIDTH 32
#define TC4_M_DO_TEST_BENCH_WIRING 0
#define TC4_M_DRIVEN_SIM_VALUE 0
#define TC4_M_EDGE_TYPE "NONE"
#define TC4_M_FREQ 50000000
#define TC4_M_HAS_IN 0
#define TC4_M_HAS_OUT 1
#define TC4_M_HAS_TRI 0
#define TC4_M_IRQ -1
#define TC4_M_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC4_M_IRQ_TYPE "NONE"
#define TC4_M_NAME "/dev/tc4_m"
#define TC4_M_RESET_VALUE 0
#define TC4_M_SPAN 16
#define TC4_M_TYPE "altera_avalon_pio"


/*
 * tc4_status configuration
 *
 */

#define ALT_MODULE_CLASS_tc4_status altera_avalon_pio
#define TC4_STATUS_BASE 0x152f0
#define TC4_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define TC4_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TC4_STATUS_CAPTURE 1
#define TC4_STATUS_DATA_WIDTH 25
#define TC4_STATUS_DO_TEST_BENCH_WIRING 1
#define TC4_STATUS_DRIVEN_SIM_VALUE 0
#define TC4_STATUS_EDGE_TYPE "RISING"
#define TC4_STATUS_FREQ 50000000
#define TC4_STATUS_HAS_IN 1
#define TC4_STATUS_HAS_OUT 0
#define TC4_STATUS_HAS_TRI 0
#define TC4_STATUS_IRQ -1
#define TC4_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC4_STATUS_IRQ_TYPE "NONE"
#define TC4_STATUS_NAME "/dev/tc4_status"
#define TC4_STATUS_RESET_VALUE 0
#define TC4_STATUS_SPAN 16
#define TC4_STATUS_TYPE "altera_avalon_pio"


/*
 * tc_reset configuration
 *
 */

#define ALT_MODULE_CLASS_tc_reset altera_avalon_pio
#define TC_RESET_BASE 0x15120
#define TC_RESET_BIT_CLEARING_EDGE_REGISTER 0
#define TC_RESET_BIT_MODIFYING_OUTPUT_REGISTER 1
#define TC_RESET_CAPTURE 0
#define TC_RESET_DATA_WIDTH 4
#define TC_RESET_DO_TEST_BENCH_WIRING 0
#define TC_RESET_DRIVEN_SIM_VALUE 0
#define TC_RESET_EDGE_TYPE "NONE"
#define TC_RESET_FREQ 50000000
#define TC_RESET_HAS_IN 0
#define TC_RESET_HAS_OUT 1
#define TC_RESET_HAS_TRI 0
#define TC_RESET_IRQ -1
#define TC_RESET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TC_RESET_IRQ_TYPE "NONE"
#define TC_RESET_NAME "/dev/tc_reset"
#define TC_RESET_RESET_VALUE 0
#define TC_RESET_SPAN 32
#define TC_RESET_TYPE "altera_avalon_pio"


/*
 * uart1_baud_control configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_baud_control altera_avalon_pio
#define UART1_BAUD_CONTROL_BASE 0x152d0
#define UART1_BAUD_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_BAUD_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_BAUD_CONTROL_CAPTURE 0
#define UART1_BAUD_CONTROL_DATA_WIDTH 30
#define UART1_BAUD_CONTROL_DO_TEST_BENCH_WIRING 0
#define UART1_BAUD_CONTROL_DRIVEN_SIM_VALUE 0
#define UART1_BAUD_CONTROL_EDGE_TYPE "NONE"
#define UART1_BAUD_CONTROL_FREQ 50000000
#define UART1_BAUD_CONTROL_HAS_IN 0
#define UART1_BAUD_CONTROL_HAS_OUT 1
#define UART1_BAUD_CONTROL_HAS_TRI 0
#define UART1_BAUD_CONTROL_IRQ -1
#define UART1_BAUD_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_BAUD_CONTROL_IRQ_TYPE "NONE"
#define UART1_BAUD_CONTROL_NAME "/dev/uart1_baud_control"
#define UART1_BAUD_CONTROL_RESET_VALUE 0
#define UART1_BAUD_CONTROL_SPAN 16
#define UART1_BAUD_CONTROL_TYPE "altera_avalon_pio"


/*
 * uart1_r_data configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_r_data altera_avalon_pio
#define UART1_R_DATA_BASE 0x152c0
#define UART1_R_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_R_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_R_DATA_CAPTURE 1
#define UART1_R_DATA_DATA_WIDTH 8
#define UART1_R_DATA_DO_TEST_BENCH_WIRING 1
#define UART1_R_DATA_DRIVEN_SIM_VALUE 0
#define UART1_R_DATA_EDGE_TYPE "RISING"
#define UART1_R_DATA_FREQ 50000000
#define UART1_R_DATA_HAS_IN 1
#define UART1_R_DATA_HAS_OUT 0
#define UART1_R_DATA_HAS_TRI 0
#define UART1_R_DATA_IRQ -1
#define UART1_R_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_R_DATA_IRQ_TYPE "NONE"
#define UART1_R_DATA_NAME "/dev/uart1_r_data"
#define UART1_R_DATA_RESET_VALUE 0
#define UART1_R_DATA_SPAN 16
#define UART1_R_DATA_TYPE "altera_avalon_pio"


/*
 * uart1_reset_control configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_reset_control altera_avalon_pio
#define UART1_RESET_CONTROL_BASE 0x15100
#define UART1_RESET_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_RESET_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define UART1_RESET_CONTROL_CAPTURE 0
#define UART1_RESET_CONTROL_DATA_WIDTH 3
#define UART1_RESET_CONTROL_DO_TEST_BENCH_WIRING 0
#define UART1_RESET_CONTROL_DRIVEN_SIM_VALUE 0
#define UART1_RESET_CONTROL_EDGE_TYPE "NONE"
#define UART1_RESET_CONTROL_FREQ 50000000
#define UART1_RESET_CONTROL_HAS_IN 0
#define UART1_RESET_CONTROL_HAS_OUT 1
#define UART1_RESET_CONTROL_HAS_TRI 0
#define UART1_RESET_CONTROL_IRQ -1
#define UART1_RESET_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_RESET_CONTROL_IRQ_TYPE "NONE"
#define UART1_RESET_CONTROL_NAME "/dev/uart1_reset_control"
#define UART1_RESET_CONTROL_RESET_VALUE 0
#define UART1_RESET_CONTROL_SPAN 32
#define UART1_RESET_CONTROL_TYPE "altera_avalon_pio"


/*
 * uart1_rx_counter configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_rx_counter altera_avalon_pio
#define UART1_RX_COUNTER_BASE 0x15290
#define UART1_RX_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_RX_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_RX_COUNTER_CAPTURE 1
#define UART1_RX_COUNTER_DATA_WIDTH 8
#define UART1_RX_COUNTER_DO_TEST_BENCH_WIRING 1
#define UART1_RX_COUNTER_DRIVEN_SIM_VALUE 0
#define UART1_RX_COUNTER_EDGE_TYPE "RISING"
#define UART1_RX_COUNTER_FREQ 50000000
#define UART1_RX_COUNTER_HAS_IN 1
#define UART1_RX_COUNTER_HAS_OUT 0
#define UART1_RX_COUNTER_HAS_TRI 0
#define UART1_RX_COUNTER_IRQ -1
#define UART1_RX_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_RX_COUNTER_IRQ_TYPE "NONE"
#define UART1_RX_COUNTER_NAME "/dev/uart1_rx_counter"
#define UART1_RX_COUNTER_RESET_VALUE 0
#define UART1_RX_COUNTER_SPAN 16
#define UART1_RX_COUNTER_TYPE "altera_avalon_pio"


/*
 * uart1_status_control configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_status_control altera_avalon_pio
#define UART1_STATUS_CONTROL_BASE 0x152a0
#define UART1_STATUS_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_STATUS_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_STATUS_CONTROL_CAPTURE 1
#define UART1_STATUS_CONTROL_DATA_WIDTH 8
#define UART1_STATUS_CONTROL_DO_TEST_BENCH_WIRING 1
#define UART1_STATUS_CONTROL_DRIVEN_SIM_VALUE 0
#define UART1_STATUS_CONTROL_EDGE_TYPE "RISING"
#define UART1_STATUS_CONTROL_FREQ 50000000
#define UART1_STATUS_CONTROL_HAS_IN 1
#define UART1_STATUS_CONTROL_HAS_OUT 0
#define UART1_STATUS_CONTROL_HAS_TRI 0
#define UART1_STATUS_CONTROL_IRQ -1
#define UART1_STATUS_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_STATUS_CONTROL_IRQ_TYPE "NONE"
#define UART1_STATUS_CONTROL_NAME "/dev/uart1_status_control"
#define UART1_STATUS_CONTROL_RESET_VALUE 0
#define UART1_STATUS_CONTROL_SPAN 16
#define UART1_STATUS_CONTROL_TYPE "altera_avalon_pio"


/*
 * uart1_tx_counter configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_tx_counter altera_avalon_pio
#define UART1_TX_COUNTER_BASE 0x152b0
#define UART1_TX_COUNTER_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_TX_COUNTER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_TX_COUNTER_CAPTURE 1
#define UART1_TX_COUNTER_DATA_WIDTH 3
#define UART1_TX_COUNTER_DO_TEST_BENCH_WIRING 1
#define UART1_TX_COUNTER_DRIVEN_SIM_VALUE 0
#define UART1_TX_COUNTER_EDGE_TYPE "RISING"
#define UART1_TX_COUNTER_FREQ 50000000
#define UART1_TX_COUNTER_HAS_IN 1
#define UART1_TX_COUNTER_HAS_OUT 0
#define UART1_TX_COUNTER_HAS_TRI 0
#define UART1_TX_COUNTER_IRQ -1
#define UART1_TX_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_TX_COUNTER_IRQ_TYPE "NONE"
#define UART1_TX_COUNTER_NAME "/dev/uart1_tx_counter"
#define UART1_TX_COUNTER_RESET_VALUE 0
#define UART1_TX_COUNTER_SPAN 16
#define UART1_TX_COUNTER_TYPE "altera_avalon_pio"


/*
 * uart1_w_data configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_w_data altera_avalon_pio
#define UART1_W_DATA_BASE 0x152e0
#define UART1_W_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_W_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define UART1_W_DATA_CAPTURE 0
#define UART1_W_DATA_DATA_WIDTH 8
#define UART1_W_DATA_DO_TEST_BENCH_WIRING 0
#define UART1_W_DATA_DRIVEN_SIM_VALUE 0
#define UART1_W_DATA_EDGE_TYPE "NONE"
#define UART1_W_DATA_FREQ 50000000
#define UART1_W_DATA_HAS_IN 0
#define UART1_W_DATA_HAS_OUT 1
#define UART1_W_DATA_HAS_TRI 0
#define UART1_W_DATA_IRQ -1
#define UART1_W_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_W_DATA_IRQ_TYPE "NONE"
#define UART1_W_DATA_NAME "/dev/uart1_w_data"
#define UART1_W_DATA_RESET_VALUE 0
#define UART1_W_DATA_SPAN 16
#define UART1_W_DATA_TYPE "altera_avalon_pio"


/*
 * uart1_wr_control configuration
 *
 */

#define ALT_MODULE_CLASS_uart1_wr_control altera_avalon_pio
#define UART1_WR_CONTROL_BASE 0x150e0
#define UART1_WR_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define UART1_WR_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define UART1_WR_CONTROL_CAPTURE 0
#define UART1_WR_CONTROL_DATA_WIDTH 2
#define UART1_WR_CONTROL_DO_TEST_BENCH_WIRING 0
#define UART1_WR_CONTROL_DRIVEN_SIM_VALUE 0
#define UART1_WR_CONTROL_EDGE_TYPE "NONE"
#define UART1_WR_CONTROL_FREQ 50000000
#define UART1_WR_CONTROL_HAS_IN 0
#define UART1_WR_CONTROL_HAS_OUT 1
#define UART1_WR_CONTROL_HAS_TRI 0
#define UART1_WR_CONTROL_IRQ -1
#define UART1_WR_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define UART1_WR_CONTROL_IRQ_TYPE "NONE"
#define UART1_WR_CONTROL_NAME "/dev/uart1_wr_control"
#define UART1_WR_CONTROL_RESET_VALUE 0
#define UART1_WR_CONTROL_SPAN 32
#define UART1_WR_CONTROL_TYPE "altera_avalon_pio"


/*
 * warn_pwm_brightness configuration
 *
 */

#define ALT_MODULE_CLASS_warn_pwm_brightness altera_avalon_pio
#define WARN_PWM_BRIGHTNESS_BASE 0x15240
#define WARN_PWM_BRIGHTNESS_BIT_CLEARING_EDGE_REGISTER 0
#define WARN_PWM_BRIGHTNESS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define WARN_PWM_BRIGHTNESS_CAPTURE 0
#define WARN_PWM_BRIGHTNESS_DATA_WIDTH 8
#define WARN_PWM_BRIGHTNESS_DO_TEST_BENCH_WIRING 0
#define WARN_PWM_BRIGHTNESS_DRIVEN_SIM_VALUE 0
#define WARN_PWM_BRIGHTNESS_EDGE_TYPE "NONE"
#define WARN_PWM_BRIGHTNESS_FREQ 50000000
#define WARN_PWM_BRIGHTNESS_HAS_IN 0
#define WARN_PWM_BRIGHTNESS_HAS_OUT 1
#define WARN_PWM_BRIGHTNESS_HAS_TRI 0
#define WARN_PWM_BRIGHTNESS_IRQ -1
#define WARN_PWM_BRIGHTNESS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define WARN_PWM_BRIGHTNESS_IRQ_TYPE "NONE"
#define WARN_PWM_BRIGHTNESS_NAME "/dev/warn_pwm_brightness"
#define WARN_PWM_BRIGHTNESS_RESET_VALUE 0
#define WARN_PWM_BRIGHTNESS_SPAN 16
#define WARN_PWM_BRIGHTNESS_TYPE "altera_avalon_pio"


/*
 * warn_pwm_control configuration
 *
 */

#define ALT_MODULE_CLASS_warn_pwm_control altera_avalon_pio
#define WARN_PWM_CONTROL_BASE 0x150a0
#define WARN_PWM_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define WARN_PWM_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define WARN_PWM_CONTROL_CAPTURE 0
#define WARN_PWM_CONTROL_DATA_WIDTH 2
#define WARN_PWM_CONTROL_DO_TEST_BENCH_WIRING 0
#define WARN_PWM_CONTROL_DRIVEN_SIM_VALUE 0
#define WARN_PWM_CONTROL_EDGE_TYPE "NONE"
#define WARN_PWM_CONTROL_FREQ 50000000
#define WARN_PWM_CONTROL_HAS_IN 0
#define WARN_PWM_CONTROL_HAS_OUT 1
#define WARN_PWM_CONTROL_HAS_TRI 0
#define WARN_PWM_CONTROL_IRQ -1
#define WARN_PWM_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define WARN_PWM_CONTROL_IRQ_TYPE "NONE"
#define WARN_PWM_CONTROL_NAME "/dev/warn_pwm_control"
#define WARN_PWM_CONTROL_RESET_VALUE 0
#define WARN_PWM_CONTROL_SPAN 32
#define WARN_PWM_CONTROL_TYPE "altera_avalon_pio"

#endif /* __SYSTEM_H_ */
